name: meu_cantinho
description: "Descubra e compartilhe os melhores lugares da cidade."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  riverpod: ^2.6.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
